APPLICATION:
  ENVIRONMENT: DEVELOPMENT
  NAME: Smart Leasing App

API:
  IS_DEBUG: False
  PORT: 6600

DATABASE:
  TYPE: SQLITE
  HOST: 'files/db/test.db'
  EXECUTION_OPTIONS:
    schema_translate_map:
      Common:

ONE_NT_DATABASE:
  TYPE: MSSQL
  DRIVER: ODBC Driver 17 for SQL Server
  HOST: TEST
  PORT:
  DATABASE: TEST
  USER: TEST
  PASSWORD: TEST

ONE_MAP_DATABASE:
  TYPE: ORACLE
  HOST: *
  PORT: 1521
  SERVICE_NAME: TEST
  USER: TEST
  PASSWORD: TEST

PROCESS:
  PROCESS_COUNT: 5

BUILDING:
  BUILDING_PROCESS_COUNT: 8
  BASE_TABLE_NAME: 'TEST'

PREDICTION_DATA:
  PREDICTION_DATA_PROCESS_COUNT: 8
  PREDICTION_DATA_TABLE_NAME: 'TEST'
AI:
    COLUMNS: ['TIP_ADI', 'KAT', 'YUKSEKLIK', 'ALANM2', 'LONGITUDE', 'LATITUDE', 'BASARID', 'MAHALLE_ADI', 'IL_ADI', 'ILCE_ADI', 'TOTAL_ALAN', 'BS_ON_BUILDING', 'REGION', 'R150', 'SCORE', 'SERVICED_BS_DISTANCE','SERVICED_BS_YEARLY_TL']

APS:
  COALESCE: False
  MAX_INSTANCES: 10
  THREAD_POOL_EXECUTER_COUNT: 10
  PROCESS_POOL_EXECUTER_COUNT: 10
  DEFAULT_MISFIRE_GRACE_TIME_DATE_JOB: 300
  DEFAULT_MISFIRE_GRACE_TIME_CRON_JOB: 300