apiVersion: v1
kind: Template
metadata:
  name: smart-leasing
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: smart-leasing
      namespace: onent-smart-leasing
      labels:
        app: smart-leasing
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ConfigChange
      replicas: 1
      test: false
      selector:
        app: smart-leasing
        deploymentconfig: smart-leasing
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: smart-leasing
            deploymentconfig: smart-leasing
        spec:
	      volumes:
	        - name: storage
	          persistentVolumeClaim:
	            claimName: storage
          containers:
            - name: smart-leasing
              image: '${REGISTRY_URL}'
              resources: {}
              imagePullPolicy: Always
	          volumeMounts:
	            - name: storage
	              mountPath: /usr/src/app/files
	          resources:
	            limits:
	              cpu: 900m
	              memory: 7Gi
	            requests:
	              cpu: 100m
	              memory: 2Gi
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
parameters:
- name: REGISTRY_URL
  displayName: OpenShift Container Registry
  description: URL of the container in Registry (baseUrl/container-name:version)
  required: true